import api from './client'
export const getCalls         = (params)        => api.get('/api/portal/calls/', { params })
export const getCall          = (id)            => api.get(`/api/portal/calls/${id}/`)
export const patchCall        = (id, data)      => api.patch(`/api/portal/calls/${id}/`, data)
export const exportCall       = (id)            => api.get(`/api/portal/calls/${id}/export/`, { responseType: 'blob' })
export const deleteCall       = (id)            => api.delete(`/api/portal/calls/${id}/delete/`)
export const deleteAllCalls   = ()              => api.delete('/api/portal/calls/delete-all/?confirm=yes')
export const bulkDeleteCalls  = (ids)           => api.post('/api/portal/calls/bulk-delete/', { ids })
export const bulkMarkCalls    = (ids, flag)     => api.post('/api/portal/calls/bulk-mark/', { ids, needs_followup: flag })
export const exportCallsCsv   = (params)        => api.get('/api/portal/calls/export-csv/', { params, responseType: 'blob' })
export const getRealtimeSummary = ()            => api.get('/api/portal/realtime/')
