# Generated by Django 4.2.29 on 2026-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_followup_sla_callprompt_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16),
        ),
    ]
