# Generated by Django 4.2.29 on 2026-04-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
