# Generated by Django 4.2.29 on 2026-04-04 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller_number', models.CharField(db_index=True, max_length=64)),
                ('audio_file_path', models.CharField(max_length=512)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('gpt_response_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('answered', 'Answered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Call Record',
                'verbose_name_plural': 'Call Records',
                'db_table': 'call_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_call_status_created')],
            },
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('transcribed', 'Transcribed'), ('answered', 'Answered'), ('failed', 'Failed'), ('retry', 'Retry')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='voice_calls.callrecord')),
            ],
            options={
                'verbose_name': 'Call Event',
                'verbose_name_plural': 'Call Events',
                'db_table': 'call_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['call', 'event_type'], name='idx_event_call_type')],
            },
        ),
    ]
