# Generated by Django 4.2.29 on 2026-04-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0003_callsession_conversationturn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callevent',
            options={'ordering': ['created_at'], 'verbose_name': 'Call Event (Legacy)', 'verbose_name_plural': 'Call Events (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='callrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Call Record (Legacy)', 'verbose_name_plural': 'Call Records (Legacy)'},
        ),
        migrations.RemoveConstraint(
            model_name='conversationturn',
            name='uq_turn_session_number',
        ),
    ]
