# Generated by Django 4.2.29 on 2026-04-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0004_alter_callevent_options_alter_callrecord_options_and_more'),
        ('voice_calls', '0004_callsession_language'),
    ]

    operations = [
    ]
