# Generated by Django 4.2.29 on 2026-04-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0005_merge_20260406_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=8),
        ),
    ]
