# Generated by Django 4.2.29 on 2026-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0007_callsession_extra_statuses_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callevent',
            options={'ordering': ['created_at'], 'verbose_name': 'Call Event (Legacy)', 'verbose_name_plural': 'Call Events (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='callrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Call Record (Legacy)', 'verbose_name_plural': 'Call Records (Legacy)'},
        ),
        migrations.AlterField(
            model_name='callsession',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=8),
        ),
    ]
